[package]
name = "yabf"
version = "0.0.1"
authors = ["eadf"]
edition = "2018"
description = "work in progress"
readme = "README.md"
repository = "https://github.com/eadf/yabf.rs"
license = "MIT OR Apache-2.0"

[dependencies]
smallvec = "^1.6.1"

[[example]]
name = "stress_test"
path = "src/stress_test.rs"

[dev-dependencies]
fnv = "1.0.7"
rand = "0.8.3"
rand_chacha = "0.3.0"
itertools = "0.10.0"
num-bigint = "0.4.0"
