name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install rust stable
        run: rustup toolchain install stable --component rustfmt --allow-downgrade
      - name: Build
        run: cargo +stable build --verbose
      - name: Run tests
        run: cargo +stable test --verbose
