name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install nightly
        run: rustup toolchain install nightly --component rustfmt --allow-downgrade
      - name: Build
        run: cargo +nightly build --verbose
      - name: Run tests
        run: cargo +nightly test --verbose
